/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const JupiterLazyRouteImport = createFileRoute('/Jupiter')()
const MarsLazyRouteImport = createFileRoute('/Mars')()
const MercuryLazyRouteImport = createFileRoute('/Mercury')()
const NeptuneLazyRouteImport = createFileRoute('/Neptune')()
const SaturnLazyRouteImport = createFileRoute('/Saturn')()
const UranusLazyRouteImport = createFileRoute('/Uranus')()
const VenusLazyRouteImport = createFileRoute('/Venus')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JupiterLazyRoute = JupiterLazyRouteImport.update({
  id: '/Jupiter',
  path: '/Jupiter',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Jupiter.lazy').then((d) => d.Route))
const MarsLazyRoute = MarsLazyRouteImport.update({
  id: '/Mars',
  path: '/Mars',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Mars.lazy').then((d) => d.Route))
const MercuryLazyRoute = MercuryLazyRouteImport.update({
  id: '/Mercury',
  path: '/Mercury',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Mercury.lazy').then((d) => d.Route))
const NeptuneLazyRoute = NeptuneLazyRouteImport.update({
  id: '/Neptune',
  path: '/Neptune',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Neptune.lazy').then((d) => d.Route))
const SaturnLazyRoute = SaturnLazyRouteImport.update({
  id: '/Saturn',
  path: '/Saturn',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Saturn.lazy').then((d) => d.Route))
const UranusLazyRoute = UranusLazyRouteImport.update({
  id: '/Uranus',
  path: '/Uranus',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Uranus.lazy').then((d) => d.Route))
const VenusLazyRoute = VenusLazyRouteImport.update({
  id: '/Venus',
  path: '/Venus',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Venus.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Jupiter': typeof JupiterLazyRoute
  '/Mars': typeof MarsLazyRoute
  '/Mercury': typeof MercuryLazyRoute
  '/Neptune': typeof NeptuneLazyRoute
  '/Saturn': typeof SaturnLazyRoute
  '/Uranus': typeof UranusLazyRoute
  '/Venus': typeof VenusLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Jupiter': typeof JupiterLazyRoute
  '/Mars': typeof MarsLazyRoute
  '/Mercury': typeof MercuryLazyRoute
  '/Neptune': typeof NeptuneLazyRoute
  '/Saturn': typeof SaturnLazyRoute
  '/Uranus': typeof UranusLazyRoute
  '/Venus': typeof VenusLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Jupiter': typeof JupiterLazyRoute
  '/Mars': typeof MarsLazyRoute
  '/Mercury': typeof MercuryLazyRoute
  '/Neptune': typeof NeptuneLazyRoute
  '/Saturn': typeof SaturnLazyRoute
  '/Uranus': typeof UranusLazyRoute
  '/Venus': typeof VenusLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Jupiter'
    | '/Mars'
    | '/Mercury'
    | '/Neptune'
    | '/Saturn'
    | '/Uranus'
    | '/Venus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Jupiter'
    | '/Mars'
    | '/Mercury'
    | '/Neptune'
    | '/Saturn'
    | '/Uranus'
    | '/Venus'
  id:
    | '__root__'
    | '/'
    | '/Jupiter'
    | '/Mars'
    | '/Mercury'
    | '/Neptune'
    | '/Saturn'
    | '/Uranus'
    | '/Venus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JupiterLazyRoute: typeof JupiterLazyRoute
  MarsLazyRoute: typeof MarsLazyRoute
  MercuryLazyRoute: typeof MercuryLazyRoute
  NeptuneLazyRoute: typeof NeptuneLazyRoute
  SaturnLazyRoute: typeof SaturnLazyRoute
  UranusLazyRoute: typeof UranusLazyRoute
  VenusLazyRoute: typeof VenusLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Jupiter': {
      id: '/Jupiter'
      path: '/Jupiter'
      fullPath: '/Jupiter'
      preLoaderRoute: typeof JupiterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Mars': {
      id: '/Mars'
      path: '/Mars'
      fullPath: '/Mars'
      preLoaderRoute: typeof MarsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Mercury': {
      id: '/Mercury'
      path: '/Mercury'
      fullPath: '/Mercury'
      preLoaderRoute: typeof MercuryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Neptune': {
      id: '/Neptune'
      path: '/Neptune'
      fullPath: '/Neptune'
      preLoaderRoute: typeof NeptuneLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Saturn': {
      id: '/Saturn'
      path: '/Saturn'
      fullPath: '/Saturn'
      preLoaderRoute: typeof SaturnLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Uranus': {
      id: '/Uranus'
      path: '/Uranus'
      fullPath: '/Uranus'
      preLoaderRoute: typeof UranusLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Venus': {
      id: '/Venus'
      path: '/Venus'
      fullPath: '/Venus'
      preLoaderRoute: typeof VenusLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JupiterLazyRoute: JupiterLazyRoute,
  MarsLazyRoute: MarsLazyRoute,
  MercuryLazyRoute: MercuryLazyRoute,
  NeptuneLazyRoute: NeptuneLazyRoute,
  SaturnLazyRoute: SaturnLazyRoute,
  UranusLazyRoute: UranusLazyRoute,
  VenusLazyRoute: VenusLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
